### ISSUE TITLE
Check package(-lock).json in validation workflow

### ISSUE THREAD

**Issue by Dudeplayz** [mcollovati/quarkus-hilla#127]
The package.json and package-lock.json should also be validated. Mostly because a dependency update from dependabot not updates these files. Additionally a auto apply feature could be added, as for the formatting check.

**Comment by mcollovati** [comment]
We now have a new workflow [Update NPM dependencies](https://github.com/mcollovati/quarkus-hilla/actions/workflows/update-npm-deps.yaml) that runs every night, building the project and creates a PR for protected branches if some `package.json` or `package-lock.json` files are modified.
It can also be triggered manually
