### ISSUE TITLE
Code style definition and checks

### ISSUE THREAD

**Issue by mcollovati** [mcollovati/quarkus-hilla#25]
Defining common code style rules prevents commits to being bloated with not significant changes, such as spaces, import order, etc.
Agree on code style and add automation for checking rules.

**Comment by mcollovati** [comment]
Some options to investigate:

* https://github.com/revelc/formatter-maven-plugin: Uses eclipse formatter, there's also a plugin for IntelliJ IDEA
* https://github.com/google/google-java-format
* https://github.com/jhipster/prettier-java

Both `google-java-format` and `prettier-java` are based on https://google.github.io/styleguide/javaguide.html, that could be pretty good

**Comment by mcollovati** [comment]
An interesting tool that can be used in addition to the ones mentioned above

https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md

**Comment by Dudeplayz** [comment]
Let's go with spotless, it's very powerful and supports different languages and formatters.
Additional to prettier and google format, I saw also https://github.com/palantir/palantir-java-format in the spotless docs, which could also be nice.
