### ISSUE TITLE
Icons in extensions docs

### ISSUE THREAD

**Issue by melloware** [mcollovati/quarkus-hilla#914]
In your `/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml` in all your extensions you need to add a new field for iconUrl.

```
icon-url: "https://raw.githubusercontent.com/vaadin/hilla/main/hilla-logo.svg"
```

That will update the docs to the Hilla logo instead of your github image.

![image](https://github.com/user-attachments/assets/a77e4434-b13d-42b0-b777-3e8ed53677bb)

**Comment by mcollovati** [comment]
Thank you for the suggestion. However, this in not an official extension, so I would not use the Hilla logo.

**Comment by melloware** [comment]
Hilla is Apache 2.0 licensed so I can't see how using their logo would violate any license terms even if its not official?

**Comment by mcollovati** [comment]
Got a confirmation from Vaadin that the Hilla logo cannot be used for a personal project.

**Comment by mcollovati** [comment]
Help in designing a custom logo would be more than appreciated :grin:

**Comment by melloware** [comment]
Here you go.  I asked ChatGPT to deisgn a non copyrighted logo that combines elements of Quarkus and Hilla.

![quarkus-hilla](https://github.com/user-attachments/assets/be1761bb-e59b-49d3-b187-7eabd730d236)

I attached the original WEBP file from CHatGPT and then i used a converter to convert to PNG to display here but WEBP i think is the preferred format.

[images.zip](https://github.com/user-attachments/files/16946807/images.zip)

**Comment by mcollovati** [comment]
This is the best I was able to produce :joy: 

![quarkus-hilla](https://github.com/user-attachments/assets/7f0d37d1-d1b8-4df3-8a6d-40f5e04263a9)

**Comment by melloware** [comment]
I like it!

**Comment by melloware** [comment]
nice!
